- alias: "Motioneye - Cameraout01 - Motion started"
  trigger:
    platform: webhook
    webhook_id: motioneye-cameraout01-started
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.cameraout01_motion_detected
- alias: "Motioneye - Cameraout01 - Motion ended"
  trigger:
    platform: webhook
    webhook_id: motioneye-cameraout01-ended
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.cameraout01_motion_detected