############################################################################
#                                                                          #
#   Home Assistant Automations                                             #
#                                                                          #
############################################################################

- alias: Purge Database
  id: Purge Database
  trigger:
  - platform: time
    at: '03:00:00'
  action:
  - service: recorder.purge
    data:
      keep_days: 8
      repack: true

- alias: Unavailable Entities Notification
  id: unavailable_entities_notification
  description: Create persistent notification if there are unavailable entities, dismiss if none.
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.unavailable_entities
  action:
    - choose:
        conditions:
          - condition: numeric_state
            entity_id: sensor.unavailable_entities
            below: 1
        sequence:
          - service: persistent_notification.dismiss
            data:
              notification_id: unavailable_entities
      default:
        - service: persistent_notification.create
          data:
            title: Unavailable Entities
            message: "- {{ expand(state_attr('sensor.unavailable_entities','entities'))|map(attribute='entity_id')|join('\n- ') }}"
            notification_id: unavailable_entities




#- alias: New Version Home Assistant
#  description: New Version Home Assistant
#  trigger:
#  - entity_id: binary_sensor.updater
#    from: 'off'
#    platform: state
#    to: 'on'
#  condition: []
#  action:
#  - data:
#      message: There is a new Home Assistant release available.
#    service: notify.mobile_app_iphone_sf
#  mode: single

- alias: Notify Hass Power Down
  description: Notify Hass Power Down
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      message: שרת הבית החכם כעת זמין
      title: הפעלת שרת הבית החכם!
      data:
        push:
          sound: "SystemStartup_Haptic.caf"            
    service: notify.mobile_app_iphone_sf
  mode: single  


- alias: Fix unknown status on sensors connected to RF
  description: 'Fix unknown status on sensors connected to RF'
  trigger:
    - platform: homeassistant
      event: start
  condition: []
  action:
    - service: python_script.set_state
      data_template:
        entity_id: binary_sensor.alarm_gassensor_kitchen
        state: 'off'
        allow_create: true
    - service: python_script.set_state
      data_template:
        entity_id: binary_sensor.alarm_doorsensor_entrance_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_gassensor_kitchen
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_gassensor_kitchen_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_motionsensor_saloon_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_motionsensor_stairs01_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_motionsensor_stairs02_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_hallfloor02
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_hallfloor02_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_kitchen
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_kitchen_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_liel
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_liel_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_maor
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_maor_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_meitar
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_meitar_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_parents
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_parents_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_room03
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_room03_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_saloon
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_smokesensor_saloon_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_floor03
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_floor03_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_kitchen
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_kitchen_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_liel
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_liel_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_maor
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_maor_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_meitar
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_meitar_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_parents
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_parents_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_saloonbig
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_saloonbig_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_saloonsmall
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_saloonsmall_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_sherut
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_windowsensor_sherut_low_battery
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_doorsensor_entrance
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_motionsensor_saloon
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_motionsensor_stairs01
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.alarm_motionsensor_stairs02
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.gly_nzylvt_mtbkh_battery_low
        state: 'off'
        allow_create: true        
    - service: python_script.set_state
      data_template:        
        entity_id: binary_sensor.gly_nzylvt_mtbkh_water_leak
        state: 'off'
        allow_create: true        




#- alias: Set Socket01 Watts To Input Sensor
#  trigger:
#    platform: time
#    minutes: 0
#    seconds: 0
#  action:
#    service: input_number.set_value
#    entity_id: input_number.socket01_watts
#    data_template:
#      value: "{{ states('sensor.socket01_energy_power') }}"


#- alias: Hass start Update Cost Sensor
#  trigger:
#  - event_type: homeassistant_start
#    platform: event
#  action:
#  - data:
#      entity_id: sensor.house_energy_kwh_cost
#      state: >              
#        {{ states.sensor.total_cost_energy_today.state }}
#    service: python_script.set_state













#- alias: Change House Mode To Normal At 00:00
#  description: Change House Mode To Normal At 00:00
#  trigger:
#  - at: 00:00:00
#    platform: time
#  condition:
#  - condition: state
#    entity_id: input_select.house_modes
#    state: '{{ states.attributes.state != Normal }}'
#  action:
#    - service: input_select.select_option
#      data:
#        entity_id: input_select.house_modes
#        option: "Normal"
#  mode: single
