#Trigger motion detection reolink01
- alias: 'Reolink01 Camera Motion'   # For reference, paste your webhook URL that you setup in Synology here: http://x.x.x.x:8123/api/webhook/motion_porch
  trigger:
    - platform: webhook
      webhook_id: reolink01_motion
  action:
#    - service: camera.snapshot
#      data:
#          entity_id: camera.synology_shl01_reolink_out01
#          filename: '/config/www/snapshot-reolink01.jpg'
    - service: input_boolean.turn_on
      entity_id: input_boolean.reolink01_motion_detected
    - delay: 00:00:05
    - service: input_boolean.turn_off
      entity_id: input_boolean.reolink01_motion_detected

#Trigger motion detection reolink02
- alias: 'Reolink02 Camera Motion'   # For reference, paste your webhook URL that you setup in Synology here: http://x.x.x.x:8123/api/webhook/motion_porch
  trigger:
    - platform: webhook
      webhook_id: reolink02_motion
  action:
#    - service: camera.snapshot
#      data:
#          entity_id: camera.synology_shl01_reolink_out02
#          filename: '/config/www/snapshot-reolink02.jpg'
    - service: input_boolean.turn_on
      entity_id: input_boolean.reolink02_motion_detected
    - delay: 00:00:05
    - service: input_boolean.turn_off
      entity_id: input_boolean.reolink02_motion_detected







    
    
    
    
    
    
 