#################### Switcher Power Changes On And Off ############################

- alias: Powercalc Switcher Changes
  description: Powercalc Switcher Changes
  trigger:
    - platform: state
      entity_id: sensor.switcher_boiler_31f2_power_consumption
  condition: 
    condition: template
    value_template: "{{ (trigger.from_state.state | float - trigger.to_state.state | float) | abs > 2 and (trigger.from_state.state | float - trigger.to_state.state | float) | abs < 4000 }}"
  action:
  - data:
      entity_id: sensor.switcher_boiler_power_state_changes
      state: >              
        off
    service: python_script.set_state
  - data:
      entity_id: sensor.switcher_boiler_power_state_changes
      state: >              
        on
    service: python_script.set_state
  mode: single          

####################################################################################

#################### Dishwasher Power Changes On And Off ############################

- alias: Powercalc Dishwasher Changes
  description: Powercalc Dishwasher Changes
  trigger:
    - platform: state
      entity_id: sensor.socket01_energy_power
  condition: 
    condition: template
    value_template: "{{ (trigger.from_state.state | float - trigger.to_state.state | float) | abs > 2 and (trigger.from_state.state | float - trigger.to_state.state | float) | abs < 4000 }}"
  action:
  - data:
      entity_id: sensor.dishwaser_power_state_changes
      state: >              
        off
    service: python_script.set_state
  - data:
      entity_id: sensor.dishwaser_power_state_changes
      state: >              
        on
    service: python_script.set_state
  mode: single          

####################################################################################

#################### Oven Power Changes On And Off ############################

- alias: Powercalc Oven Changes
  description: Powercalc Oven Changes
  trigger:
    - platform: state
      entity_id: sensor.socket02_energy_power
  condition: 
    condition: template
    value_template: "{{ (trigger.from_state.state | float - trigger.to_state.state | float) | abs > 2 and (trigger.from_state.state | float - trigger.to_state.state | float) | abs < 4000 }}"
  action:
  - data:
      entity_id: sensor.oven_power_state_changes
      state: >              
        off
    service: python_script.set_state
  - data:
      entity_id: sensor.oven_power_state_changes
      state: >              
        on
    service: python_script.set_state
  mode: single          

####################################################################################

#################### Microgal Power Changes On And Off ############################

- alias: Powercalc Microgal Changes
  description: Powercalc Microgal Changes
  trigger:
    - platform: state
      entity_id: sensor.socket03_energy_power
  condition: 
    condition: template
#    value_template: "{{ (trigger.from_state.state | float - trigger.to_state.state | float) | abs > 2 and (trigger.from_state.state | float - trigger.to_state.state | float) | abs < 4000 }}"
    value_template: '{{ trigger.to_state.state | float != trigger.from_state.state | float }}'
  action:
  - data:
      entity_id: sensor.microgal_power_state_changes
      state: >              
        off
    service: python_script.set_state
  - data:
      entity_id: sensor.microgal_power_state_changes
      state: >              
        on
    service: python_script.set_state
  mode: single          

####################################################################################

#################### Washing Machine Power Changes On And Off ############################

- alias: Powercalc Washing Machine Changes
  description: Powercalc Washing Machine Changes
  trigger:
    - platform: state
      entity_id: sensor.socket04_energy_power
  condition: 
    condition: template
    value_template: "{{ (trigger.from_state.state | float - trigger.to_state.state | float) | abs > 2 and (trigger.from_state.state | float - trigger.to_state.state | float) | abs < 4000 }}"
  action:
  - data:
      entity_id: sensor.washing_machine_power_state_changes
      state: >              
        off
    service: python_script.set_state
  - data:
      entity_id: sensor.washing_machine_power_state_changes
      state: >              
        on
    service: python_script.set_state
  mode: single          

####################################################################################

#################### Kitchen Devices Power Changes On And Off ############################

- alias: Powercalc Kitchen Devices Changes
  description: Powercalc Kitchen Devices Changes
  trigger:
    - platform: state
      entity_id: sensor.socket05_energy_power
  condition: 
    condition: template
    value_template: "{{ (trigger.from_state.state | float - trigger.to_state.state | float) | abs > 2 and (trigger.from_state.state | float - trigger.to_state.state | float) | abs < 4000 }}"
  action:
  - data:
      entity_id: sensor.kitchen_devices_power_state_changes
      state: >              
        off
    service: python_script.set_state
  - data:
      entity_id: sensor.kitchen_devices_power_state_changes
      state: >              
        on
    service: python_script.set_state
  mode: single          

####################################################################################
