#Broadlink RM Pro

- platform: broadlink
  mac: '00:00:00:00:00:00'
  switches:
    
    - name: "tvxx_flxxx"
      command_on:   'JgCMAJaRFTUUNRQ2FBAVEBQRFBEUEBQ2FDUUNRUQFBEUERQQFRAUERQ1FBEUERQQFBEUERQQFTUUERQ1FDUVNRQ1FDUVNRQA111111111111111111111111BAUERQRFBAVNRQ1FDYUEBQRFBEUEBUQFBEUNRUQFBEUEBUQFBEUERQ1FBEUNRQ1FTUUNRU1FDUUAA0FAAAAAAAAAAAAAAAA'
      command_off:   'JgCMAJaRFTUUNRQ2FBAVEBQRFBEUEBQ2FDUUNRUQFBEUERQQFRAUERQ1FBEUERQQFBEUERQQFTUUERQ1FDUVNRQ1FDUVNRQ111111111111111111111111RFBAVNRQ1FDYUEBQRFBEUEBUQFBEUNRUQFBEUEBUQFBEUERQ1FBEUNRQ1FTUUNRU1FDUUAA0FAAAAAAAAAAAAAAAA'
